name: Run Robot Framework Tests
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  robot-tests:
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Chrome dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        
    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-requests
        pip install robotframework-seleniumlibrary
        pip install selenium 

    # Step 5: Set up Chrome options for headless mode
    - name: Set up Chrome options
      run: |
        echo "Setting up Chrome options..."
        export CHROME_OPTIONS="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222"
 
    # Step 4: Run Robot Framework tests
    - name: Run Tests
      run: |
         xvfb-run robot --variable BROWSER:chrome --variable CHROME_OPTIONS:"$CHROME_OPTIONS" AutomationProject/TestCases
 
    # Step 5: Upload Test Results (Optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: AutomationProject/Results
