name: Run Robot Framework Tests

# Define the events that trigger the workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Define the job for running API tests
  Robot_Api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests

      - name: Run API Tests
        run: |
          mkdir -p results/api
          robot --outputdir results/api AutomationProject/APITestCases

      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-api-results
          path: results/api/

 # Define the job for running UI tests
  Robot_UI-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdrivermanager
          webdrivermanager chrome:latest

      - name: Run UI Tests
        run: |
          robot --outputdir results/ui AutomationProject/UITestCases

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-ui-results
          path: results/ui/
