name: Run Robot Framework Tests
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  robot-tests:
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
 
    # Step 4: Run Robot Framework tests
    - name: Run Tests
      run: |
        robot AutomationProject/APITestCases
 
    # Step 5: Upload Test Results (Optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: results/
