name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job for running API tests
  api-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-requests

    # Step 4: Run Robot Framework API tests
    - name: Run API Tests
      run: |
        mkdir -p results/api
        robot --outputdir results/api AutomationProject/APITestCases

    # Step 5: Upload API Test Results
    - name: Upload API Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-api-results
        path: results/api/

  # Job for running UI tests
  ui-tests:
    runs-on: ubuntu-latest
    needs: api-tests  # Optional: Ensure API tests run before UI tests

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Use Robot Framework GitHub Action
    - name: Run Robot Framework UI Tests
      uses: tarathep/robotframework-github-action@v1.0
      with:
        image: kietara/robot-framework
        image_version: '1.0'
        tests_dir: '${{ github.workspace }}/tests/robot'
        reports_dir: '${{ github.workspace }}/tests/robot/reports'

    # Step 3: Execute Robot Framework Tests
    - name: Run Robot Framework Tests
      run: |
        robot --outputdir results/ui \
          --variable BROWSER:chrome \
          --variable CHROME_ARGUMENTS:--headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu \
          AutomationProject/TestCases
