name: Run Robot Framework Tests
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  robot-tests:
    runs-on: ubuntu-latest
 
    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 4: Install ChromeDriver
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip
        
    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-requests
        pip install robotframework-seleniumlibrary
        pip install selenium 
 
    # Step 4: Run Robot Framework tests
    - name: Run Tests
      run: |
        robot AutomationProject
 
    # Step 5: Upload Test Results (Optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: AutomationProject/Results
