name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Job for running API tests
  api-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-requests

    # Step 4: Run Robot Framework API tests
    - name: Run API Tests
      run: |
        mkdir -p results/api
        robot --outputdir results/api AutomationProject/APITestCases

    # Step 5: Upload API Test Results
    - name: Upload API Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-api-results
        path: results/api/

  # Job for running UI tests
  ui-tests:
    runs-on: ubuntu-latest
    needs: api-tests  # Optional: Ensure API tests run before UI tests

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v3

      # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install webdrivermanager

    # Step 4: Set up ChromeDriver
    - name: Set up ChromeDriver
      run: |
        webdrivermanager chrome:latest

    # Step 5: Install Google Chrome
    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Step 6: Run Robot Framework UI tests
    - name: Run UI Tests
      run: |
        mkdir -p results/ui
        robot --outputdir results/ui \
          --variable BROWSER:chrome \
          --variable CHROME_ARGUMENTS:--headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu \
          AutomationProject/TestCases

    # Step 7: Upload UI Test Results
    - name: Upload UI Test Results
      uses: actions/upload-artifact@v3
      with:
        name: robot-ui-results
        path: results/ui/
